# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textcomment', models.CharField(max_length=100)),
                ('likecom', models.CharField(default='+', max_length=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('conten', models.TextField()),
                ('timecreated', models.DateTimeField(verbose_name='Data Created')),
            ],
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='comtopost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcoment.PostModel'),
        ),
    ]
