# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcoment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Com',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textcomment', models.CharField(max_length=100)),
                ('likecom', models.CharField(default='+', max_length=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='comtopost',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='timecreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Created'),
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.AddField(
            model_name='com',
            name='comtopost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcoment.CommentList'),
        ),
    ]
